WebApplication2/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    
    public class RegisterController : Controller
    {
        readonly LoginContext _loginContext;
        public RegisterController(LoginContext loginContext) //注入服務
        {
            _loginContext = loginContext;
        }
        public IActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public IActionResult regist([FromBody] RegisterModel model)
        {
           
            var registEnd = _loginContext.Logintables.Where(w => model.Account == w.Account).ToList();//把where拿掉很多比
            if (registEnd.Count > 0)
            {
                return Ok(false);
            }
            else
            {
             Logintable data = new Logintable(); //實體化table
            data.Account = model.Account;  //將前端傳進來的model值帶進data(資料庫中)
            data.Password = model.Password;
            data.Name = model.Name;
            data.Phone = model.Phone;


            _loginContext.Add(data); //ef core新增資料
            _loginContext.SaveChanges(); //更新資料

                return Ok(true);
            }

            
                        
        }

    }
}

WebApplication2/Controllers/loginController.cs
using GridMvc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Encodings.Web;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class loginController : Controller
    { 
        readonly LoginContext _loginContext;
        public loginController(LoginContext loginContext) //注入服務
        {
            _loginContext = loginContext;
        }

       
        public IActionResult loginIndex()
        {
            return View();
        }

        public IActionResult home(RegisterModel data)
        {
            
            var loginEnd = _loginContext.Logintables.Where(w => data.Account == w.Account && data.Password == w.Password).FirstOrDefault();
            var value = new RegisterModel();
            value.Account = loginEnd.Account;
            value.Password = loginEnd.Password;
            value.Phone = loginEnd.Phone;
            value.Name = loginEnd.Name;

           
            return View(value);
        }

        [HttpPost]
        public IActionResult login([FromBody]RegisterModel data)
        {
            
           var loginEnd = _loginContext.Logintables.Where(w => data.Account == w.Account && data.Password == w.Password).ToList();//把where拿掉很多比
           if(loginEnd.Count > 0)
            {
                return Ok(true);
            }
           else
            {
                
                return Ok(false);
            }
          
        }

        

        public IActionResult modify(RegisterModel model)
        {
            
            
            var modify = _loginContext.Logintables.Where(w => model.Account == w.Account && model.Password == w.Password).FirstOrDefault();
            modify.Account = model.Account;
            modify.Password = model.newPassword;
            modify.Phone = model.Phone;
            modify.Name = model.Name;

            _loginContext.Update(modify);
            _loginContext.SaveChanges();
            return RedirectToAction("loginIndex");


        }

       
        }
}

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 查詢系統</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">WebApplication2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="login" asp-action="loginIndex">登入</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index">註冊</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">查詢</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>